[package]
name = "harmonics-generator"
description = ""
version = "0.1.0"
license = ""
edition = "2021"

# MSRV
rust-version = "1.65.0"

[features]
default = []
foobar = []

[dependencies]
tts = "0.26.3"
